// Debug script for transcript viewing issues
console.log('🔍 Debugging Transcript Viewing Issues')
console.log('=' .repeat(60))

console.log('\n📋 Common Issues to Check:')
console.log('1. Database connection problems')
console.log('2. Incorrect call_id values')
console.log('3. Missing transcript data in database')
console.log('4. JavaScript errors in console')
console.log('5. Dialog not opening due to state issues')

console.log('\n🔧 Debugging Steps:')
console.log('\nStep 1: Check if call_id exists in evaluation results')
console.log('- Open browser dev tools')
console.log('- Go to Network tab')
console.log('- Look at the evaluation results API response')
console.log('- Verify call_id field is present and not null')

console.log('\nStep 2: Check database tables')
console.log('- Verify pype_voice_call_logs has entries with matching call_id')
console.log('- Verify pype_voice_metrics_logs has transcript data')
console.log('- Check the session_id relationship')

console.log('\nStep 3: Check console logs when clicking View Transcript')
console.log('Expected logs:')
console.log('✅ "Fetching transcript for call_id: [some-id]"')
console.log('✅ "Found call log ID: [internal-id] for call_id: [external-id]"')  
console.log('✅ "Transcript turns found: [number]"')

console.log('\nStep 4: Common Error Patterns')
console.log('❌ "No call log found for call_id: [id]"')
console.log('   → call_id doesn\'t exist in pype_voice_call_logs')
console.log('❌ "No transcript turns found for session_id: [id]"')
console.log('   → No transcript data in pype_voice_metrics_logs')
console.log('❌ "Error fetching transcript: [error]"')
console.log('   → Database connection or permission issue')

console.log('\n🎯 Quick Fixes to Try:')
console.log('1. Check if call_id is null/undefined in results')
console.log('2. Verify Supabase connection is working')
console.log('3. Check if transcript data exists for the specific call')
console.log('4. Ensure dialog state management is working')

console.log('\n🔍 Test Query Examples:')
console.log('\n-- Check if call logs exist:')
console.log('SELECT id, call_id FROM pype_voice_call_logs LIMIT 5;')

console.log('\n-- Check if transcript data exists:')
console.log('SELECT session_id, user_transcript, agent_response')
console.log('FROM pype_voice_metrics_logs') 
console.log('WHERE user_transcript IS NOT NULL OR agent_response IS NOT NULL')
console.log('LIMIT 5;')

console.log('\n-- Check specific call relationship:')
console.log('SELECT cl.id, cl.call_id, COUNT(ml.id) as transcript_count')
console.log('FROM pype_voice_call_logs cl')
console.log('LEFT JOIN pype_voice_metrics_logs ml ON cl.id = ml.session_id')
console.log('GROUP BY cl.id, cl.call_id')
console.log('LIMIT 10;')

console.log('\n🚨 If transcript still not showing:')
console.log('1. Data may not exist in database')
console.log('2. Wrong table relationships')
console.log('3. Supabase permissions issue')
console.log('4. Frontend state management problem')
console.log('5. Dialog component not rendering')

console.log('\n💡 Next Steps:')
console.log('- Check browser console for error messages')
console.log('- Verify actual data exists in database')
console.log('- Test with known working call_id')
console.log('- Add more detailed logging to identify exact failure point')