name: Deploy Whispey

on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: secrets 

    steps:
     - name: Deploy Whispey
       run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \ 
              -J ${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}:${{ secrets.JUMPHOST_PORT }} \
              ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_HOST }} << 'EOF'

            set -e

            cd /home/ritik-intel/aditya/whispey
            git fetch origin
            git checkout main
            git pull origin main

            docker compose -f docker-compose-local.yml build
            docker compose -f docker-compose-local.yml up -d 
          
          EOF

  